export const SERVICE_TAG = {
  AppConfig: "app/AppConfig",
  Database: "app/Database",
  Translator: "app/Translator",
  Clock: "app/Clock",
  Mailer: "app/Mailer",
  Crypto: "app/Crypto",
  RateLimiter: "app/RateLimiter",
  ObjectStore: "app/ObjectStore",

  Users: "app/Users",
  Sessions: "app/Sessions",
  ApiKeys: "app/ApiKeys",
  PasswordHasher: "app/PasswordHasher",
  AuditLog: "app/AuditLog",
  UniversalAuth: "app/UniversalAuth",

  Monitors: "app/Monitors",
  Runs: "app/Runs",
  Extractors: "app/Extractors",
  MonitorRepository: "app/MonitorRepository",
  UserRepository: "app/UserRepository",
  SessionRepository: "app/SessionRepository",
  ApiKeyRepository: "app/ApiKeyRepository",
  VerificationTokenRepository: "app/VerificationTokenRepository",
  RunRepository: "app/RunRepository",
  ChangeRepository: "app/ChangeRepository",
  ChannelRepository: "app/ChannelRepository",
  RuleRepository: "app/RuleRepository",
  Rules: "app/Rules",
  Deliveries: "app/Deliveries",
  DeliveryRepository: "app/DeliveryRepository",
  Channels: "app/Channels",

  StrategyRegistry: "app/StrategyRegistry",
  HttpStrategy: "app/HttpStrategy",
  BrowserStrategy: "app/BrowserStrategy",
  Extraction: "app/Extraction",
  TransformPipeline: "app/TransformPipeline",
  ContentNormalizer: "app/ContentNormalizer",
  RobotsCache: "app/RobotsCache",
  UrlGuard: "app/UrlGuard",

  ScrapeRunner: "app/ScrapeRunner",
  Differ: "app/Differ",
  RuleEvaluator: "app/RuleEvaluator",

  ChannelSet: "app/ChannelSet",
  ChannelRegistry: "app/ChannelRegistry",
  NotificationDispatcher: "app/NotificationDispatcher",
  TemplateRenderer: "app/TemplateRenderer",

  JobProducer: "app/JobProducer",
  QueueRegistry: "app/QueueRegistry",
  RedisClient: "app/RedisClient",
  NotifyRunner: "app/NotifyRunner",
} as const

export type ServiceTag = (typeof SERVICE_TAG)[keyof typeof SERVICE_TAG]
