export const SPAN = {
  monitors: {
    create: "Monitors.create",
    update: "Monitors.update",
    remove: "Monitors.remove",
    findById: "Monitors.findById",
    list: "Monitors.list",
    preview: "Monitors.preview",
    runNow: "Monitors.runNow",
  },
  auth: {
    register: "Auth.register",
    login: "Auth.login",
    logout: "Auth.logout",
    authenticate: "Auth.authenticate",
    resetPassword: "Auth.resetPassword",
    verifyEmail: "Auth.verifyEmail",
    hashPassword: "Auth.hashPassword",
    verifyPassword: "Auth.verifyPassword",
    checkPasswordPolicy: "Auth.checkPasswordPolicy",
    findUser: "Auth.findUser",
    updateProfile: "Auth.updateProfile",
    changePassword: "Auth.changePassword",
    requestPasswordReset: "Auth.requestPasswordReset",
    requestEmailVerification: "Auth.requestEmailVerification",
    issueToken: "Auth.issueToken",
    consumeToken: "Auth.consumeToken",
    createSession: "Auth.createSession",
    listSessions: "Auth.listSessions",
    revokeSession: "Auth.revokeSession",
    revokeAllSessions: "Auth.revokeAllSessions",
    touchSession: "Auth.touchSession",
    createApiKey: "Auth.createApiKey",
    listApiKeys: "Auth.listApiKeys",
    revokeApiKey: "Auth.revokeApiKey",
    verifyApiKey: "Auth.verifyApiKey",
    rateLimit: "Auth.rateLimit",
    audit: "Auth.audit",
    sendMail: "Auth.sendMail",
    verifyBearer: "Auth.verifyBearer",
    provisionUser: "Auth.provisionUser",
    bootstrapAdmin: "Auth.bootstrapAdmin",
  },
  scraping: {
    fetch: "Scraping.fetch",
    extract: "Scraping.extract",
    normalize: "Scraping.normalize",
    transform: "Scraping.transform",
    robots: "Scraping.robots",
    checkUrl: "Scraping.checkUrl",
    resolveStrategy: "Scraping.resolveStrategy",
    preview: "Scraping.preview",
  },
  runs: {
    execute: "Runs.execute",
    diff: "Runs.diff",
    evaluateRules: "Runs.evaluateRules",
    persist: "Runs.persist",
    list: "Runs.list",
    findById: "Runs.findById",
    listChanges: "Runs.listChanges",
    series: "Runs.series",
    trigger: "Runs.trigger",
  },
  runRepository: {
    start: "RunRepository.start",
    finish: "RunRepository.finish",
    findByJobId: "RunRepository.findByJobId",
    previousSuccessful: "RunRepository.previousSuccessful",
    insertFieldValues: "RunRepository.insertFieldValues",
    fieldValues: "RunRepository.fieldValues",
    insertChanges: "RunRepository.insertChanges",
    insertSnapshot: "RunRepository.insertSnapshot",
    list: "RunRepository.list",
    findById: "RunRepository.findById",
    listChanges: "RunRepository.listChanges",
  },
  notifications: {
    dispatch: "Notifications.dispatch",
    render: "Notifications.render",
    send: "Notifications.send",
    verify: "Notifications.verify",
  },
  channels: {
    list: "Channels.list",
    listKinds: "Channels.listKinds",
    create: "Channels.create",
    update: "Channels.update",
    remove: "Channels.remove",
    test: "Channels.test",
  },
  channelRepository: {
    insert: "ChannelRepository.insert",
    update: "ChannelRepository.update",
    remove: "ChannelRepository.remove",
    findById: "ChannelRepository.findById",
    list: "ChannelRepository.list",
    incrementFailureCount: "ChannelRepository.incrementFailureCount",
    markVerified: "ChannelRepository.markVerified",
    getSecret: "ChannelRepository.getSecret",
  },
  deliveryRepository: {
    insert: "DeliveryRepository.insert",
    updateStatus: "DeliveryRepository.updateStatus",
    list: "DeliveryRepository.list",
    listFiltered: "DeliveryRepository.listFiltered",
    findById: "DeliveryRepository.findById",
  },
  deliveries: {
    list: "Deliveries.list",
    retry: "Deliveries.retry",
  },
  ruleRepository: {
    list: "RuleRepository.list",
    markFired: "RuleRepository.markFired",
    insert: "RuleRepository.insert",
    findById: "RuleRepository.findById",
    listForMonitor: "RuleRepository.listForMonitor",
    update: "RuleRepository.update",
    remove: "RuleRepository.remove",
  },
  rules: {
    list: "Rules.list",
    create: "Rules.create",
    update: "Rules.update",
    remove: "Rules.remove",
  },
  crypto: {
    encrypt: "Crypto.encrypt",
    decrypt: "Crypto.decrypt",
  },
  mailer: {
    send: "Mailer.send",
  },
  jobs: {
    scrape: "job.scrape",
    notify: "job.notify",
    digest: "job.digest",
    maintenance: "job.maintenance",
    upsertSchedule: "JobProducer.upsertSchedule",
  },
  jobProducer: {
    removeSchedule: "JobProducer.removeSchedule",
    enqueueScrape: "JobProducer.enqueueScrape",
    enqueueNotify: "JobProducer.enqueueNotify",
    enqueueDigest: "JobProducer.enqueueDigest",
    upsertDigestSchedule: "JobProducer.upsertDigestSchedule",
    removeDigestSchedule: "JobProducer.removeDigestSchedule",
    enqueueMaintenance: "JobProducer.enqueueMaintenance",
    ensureMaintenanceSchedules: "JobProducer.ensureMaintenanceSchedules",
  },
  rateLimiter: {
    checkDomain: "RateLimiter.checkDomain",
  },
  digest: {
    flush: "Digest.flush",
  },
  maintenance: {
    reconcileSchedules: "Maintenance.reconcileSchedules",
    sweepRuns: "Maintenance.sweepRuns",
    sweepSessions: "Maintenance.sweepSessions",
    refreshStats: "Maintenance.refreshStats",
    pruneRobots: "Maintenance.pruneRobots",
    schedulerHealth: "Maintenance.schedulerHealth",
  },
  admin: {
    stats: "Admin.stats",
    queues: "Admin.queues",
  },
  storage: {
    put: "ArtifactStore.put",
    get: "ArtifactStore.get",
  },
  db: {
    query: "Database.query",
    transaction: "Database.transaction",
    migrate: "Database.migrate",
  },
} as const

export const METRIC = {
  jobsProcessed: "jobs_processed_total",
  jobDuration: "job_duration_seconds",
  queueDepth: "queue_depth",
  scrapeBytes: "scrape_bytes_total",
  scrapeDuration: "scrape_duration_seconds",
  changesDetected: "changes_detected_total",
  notificationsSent: "notifications_sent_total",
  notificationsSuppressed: "notifications_suppressed_total",
  rateLimitDeferred: "rate_limit_deferred_total",
  schedulerLastFireAge: "scheduler_last_fire_age_seconds",
  httpRequests: "http_requests_total",
  httpDuration: "http_request_duration_seconds",
} as const

export const LOG_EVENT = {
  run: {
    started: "run.started",
    resumed: "run.resumed",
    skipped: "run.skipped",
    unchanged: "run.unchanged",
    diffed: "run.diffed",
    finished: "run.finished",
    failed: "run.failed",
  },
  scrape: {
    robots: "scrape.robots",
    strategy: "scrape.strategy",
    fetched: "scrape.fetched",
    escalated: "scrape.escalated",
    extracted: "scrape.extracted",
    warning: "scrape.warning",
    normalized: "scrape.normalized",
  },
  browser: {
    connected: "browser.connected",
    navigated: "browser.navigated",
    step: "browser.step",
    captured: "browser.captured",
  },
  screenshot: {
    stored: "screenshot.stored",
    failed: "screenshot.failed",
  },
} as const

export const LOG_FIELD = {
  requestId: "requestId",
  userId: "userId",
  monitorId: "monitorId",
  runId: "runId",
  ruleId: "ruleId",
  channelId: "channelId",
  deliveryId: "deliveryId",
  jobId: "jobId",
  queue: "queue",
  strategy: "strategy",
  host: "host",
  durationMs: "durationMs",
  errorTag: "errorTag",
  path: "path",
  cause: "cause",
  migrationFile: "migrationFile",
  migrationsApplied: "migrationsApplied",
  trigger: "trigger",
  attempt: "attempt",
  url: "url",
  finalUrl: "finalUrl",
  httpStatus: "httpStatus",
  bytes: "bytes",
  contentHash: "contentHash",
  status: "status",
  changed: "changed",
  changeCount: "changeCount",
  fieldCount: "fieldCount",
  missingCount: "missingCount",
  warningCount: "warningCount",
  warningCode: "warningCode",
  allowed: "allowed",
  reason: "reason",
  stepKind: "stepKind",
  screenshotRef: "screenshotRef",
} as const

export const REDACTED_KEYS = [
  "password",
  "passwordHash",
  "token",
  "tokenHash",
  "secret",
  "apiKey",
  "authorization",
  "cookie",
  "sessionToken",
  "encryptionKey",
  "smtpPassword",
  "botToken",
  "webhookUrl",
] as const
