import { writeFileSync } from "node:fs"
import { dirname, resolve } from "node:path"
import { fileURLToPath } from "node:url"

import { ENV_SPEC, envGroups } from "../src/config/env-spec.js"

const here = dirname(fileURLToPath(import.meta.url))
const target = resolve(here, "../../../deploy/.env.example")

const SECRET_HINT = "generate with: openssl rand -base64 32"

const lines: string[] = [
  "# Generated by `pnpm gen:env` from packages/core/src/config/env-spec.ts",
  "# Edit the spec, not this file.",
  "",
]

for (const group of envGroups()) {
  lines.push(`# ${"=".repeat(70)}`, `# ${group}`, `# ${"=".repeat(70)}`, "")
  for (const entry of ENV_SPEC.filter((item) => item.group === group)) {
    lines.push(`# ${entry.description}`)
    if (entry.required) lines.push("# required")
    if (entry.secret) lines.push(`# secret, ${SECRET_HINT}`)
    lines.push(`${entry.name}=${entry.secret ? "" : (entry.defaultValue ?? "")}`, "")
  }
}

writeFileSync(target, `${lines.join("\n").trimEnd()}\n`, "utf8")
globalThis.console.log(`wrote ${ENV_SPEC.length} variables to ${target}`)
