import { writeFileSync } from "node:fs"
import path from "node:path"
import { fileURLToPath } from "node:url"

import { ENV_SPEC, environmentGroups } from "../src/config/environment-spec.js"

const here = path.dirname(fileURLToPath(import.meta.url))
const target = path.resolve(here, "../../../deploy/.env.example")

const SECRET_HINT = "generate with: openssl rand -base64 32"

const lines: string[] = [
  "# Generated by `pnpm gen:env` from packages/core/src/config/environment-spec.ts",
  "# Edit the spec, not this file.",
  "",
]

for (const group of environmentGroups()) {
  const entries = ENV_SPEC.filter((item) => item.group === group)
  lines.push(`# ${"=".repeat(70)}`, `# ${group}`, `# ${"=".repeat(70)}`, "")
  for (const entry of entries) {
    lines.push(`# ${entry.description}`)
    if (entry.isRequired) lines.push("# required")
    if (entry.isSecret) lines.push(`# secret, ${SECRET_HINT}`)
    lines.push(`${entry.name}=${entry.isSecret ? "" : (entry.defaultValue ?? "")}`, "")
  }
}

writeFileSync(target, `${lines.join("\n").trimEnd()}\n`, "utf8")
globalThis.console.log(`wrote ${String(ENV_SPEC.length)} variables to ${target}`)
