services:
  api:
    build:
      context: ..
      dockerfile: deploy/Dockerfile.api
      args:
        APP_VERSION: ${APP_VERSION:-dev}
        GIT_SHA: ${GIT_SHA:-local}
      cache_from:
        - type=gha

  worker:
    build:
      context: ..
      dockerfile: deploy/Dockerfile.worker
      args:
        APP_VERSION: ${APP_VERSION:-dev}
        GIT_SHA: ${GIT_SHA:-local}
      cache_from:
        - type=gha

  web:
    build:
      context: ..
      dockerfile: deploy/Dockerfile.web
      args:
        APP_VERSION: ${APP_VERSION:-dev}
        GIT_SHA: ${GIT_SHA:-local}
      cache_from:
        - type=gha
